baseurl = "https://trichterwolke.github.io/specktakel/"
languageCode = "de-de"
title = "Mittelalterliches Specktakel"
theme = "specktakel"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Mittelalterliches Specktakel"

		[params.navigation.links]
			highlights = "Highlights"
			agenda = "Tagesprogramm"
			contact = "Kontakt"
			location = "Veranstaltungsort"

	# Hero section
	[params.hero]
		firstHeadline = "Mittelalterliches"
		secondHeadline = "Spe“c”ktakel"
		date = "23. + 24.09.2017"
		location = "Braunschweig Gliesmarode"


	# About section
	[params.about]
		headline    = "Seid gerüßt Freunde des mittelalterliches Treibens"
		description = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."

	[params.program]
		title = "Weiters Programm"

		[[params.program.items]]
				title = "Hornarbeiten"
				
		[[params.program.items]]
				title = "Steinmetz"
				
		[[params.program.items]]
				title = "Lederarbeiten"
				
		[[params.program.items]]
				title = "Kinderprogramm mit Quiz"
				
		[[params.program.items]]
				title = "Glasperlen"
				
		[[params.program.items]]
				title = "Diamantensieben"
				
		[[params.program.items]]
				title = "Steinmetz"
				
		[[params.program.items]]
				title = "Gewandschneiderei"
				
		[[params.program.items]]
				title = "Lagerwache"

	# Contact section
	[params.contact]
		phone = "+49-160-97363699"
		email = "trichterwolke@outlook.com"
		facebook = "https://facebook.com/BSCastellum"

	# Google Maps section
	 [params.location]
	 	latitude  = "52.27721"
	 	longitude = "10.55484"
	    address = "Am Soolanger 1, 38104 Braunschweig"
		content = "<b>BegegnungsZentrum</b><br>Am Soolanger 1<br>38104 Braunschweig"
	 	maps_api_key = "AIzaSyAy5fmQodq5Cf3UbFPxuEJ4nb6AavuuY_Q"
