baseurl = "http://www.mittelaltermarkt-braunschweig.de"
languageCode = "de-de"
title = "Mittelalterliches Specktakel – Mittelaltermarkt in Braunschweig"
theme = "specktakel"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Thomas Rösler"
	description = "Das 4. mittelalterliche Specktakel ist ein Mittelaltermarkt in Braunschweig Gliesmarode"

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "Mittelalterliches Specktakel"

		[params.navigation.links]
			highlights = "Highlights"
			location = "Anfahrt"
			agenda = "Programm"
			contact = "Kontakt"

	# Hero section
	[params.hero]
		firstHeadline = "Mittelalterliches"
		secondHeadline = "Spe“c”ktakel"
		date = "23. + 24.09.2017"
		location = "Mittelaltermarkt<br>Braunschweig Gliesmarode"


	# About section
	[params.about]
		headline    = "Seid gegrüßt, Freunde des mittelalterliches Treibens"
		description = """zum 4. Mal findet das mittelalterliche Spe“c”ktakel 2017 in Braunschweig statt.

Was einmal kleiner Mittelatlermarkt und nur auf dem Gelände des SoVD begann, wird nun zum vierten Mal auf der ehemaligen Festwiese des Stadtteils Gliesmarode stattfinden. 

Im **BegegnungsZentrum Gliesmarode** wird es eine Ausstellung zum 100 jährigen Bestehen des SoVD geben. 
Ebenso sind dieses mal das Schwimmbad Gliesmarode, der Schützenverein Gliesmarode sowie der Kleingartenverein Gliesmarode mit an Bord und werden jeweils Attraktionen bieten.

Wir haben ein buntes Veranstaltungsprogramm zum Staunen, Mitmachen und Genießen für euch zusammengestellt und hoffen, euch wieder bestens unterhalten zu können. 

Für das leibliche Wohl ist natürlich auch wieder gesorgt: 
Ob wohlschmeckendes Pfannenbrot, Bratwurst, veganer Eintopf oder Met aus eigener Herstellung – hier ist für jeden etwas dabei. 

Viel Spaß auf dem **4. mittelalterlichen Markt** wünschen euch die Organisatoren und alle Markttreibenden. 
 
Euer Orgateam:  
**Ulf der Bäcker** (Thomas Rösler) / Organisatorisches / Marktvoigt  
**Jens Leipelt** / Organisatorisches  
**Boris Pawlik** / Organisatorisches"""

	[params.program]
		headline = "Weiters Angebot"

		[[params.program.items]]
				title = "Hornarbeiten"
				
		[[params.program.items]]
				title = "Steinmetz"
				
		[[params.program.items]]
				title = "Lederarbeiten"
				
		[[params.program.items]]
				title = "Kinderprogramm mit Quiz"
				
		[[params.program.items]]
				title = "Glasperlen"
				
		[[params.program.items]]
				title = "Diamantensieben"
				
		[[params.program.items]]
				title = "Gewandschneiderei"
				
		[[params.program.items]]
				title = "Lagerwache"

		[[params.program.items]]
				title = "Vegane Küche"
				
		[[params.program.items]]
				title = "Rostbratwurst"

		[[params.program.items]]
				title = "Stockbrot"

	[[params.agenda]]
		headline = "Programmablauf"

	# Google Maps section
	[params.location]
	    headline = "Hier sind wir zu finden"
	 	latitude  = "52.27721"
	 	longitude = "10.55484"
	    address = "Am Soolanger 1, 38104 Braunschweig"
		content = "<b>BegegnungsZentrum</b><br>Am Soolanger 1<br>38104 Braunschweig"
	 	maps_api_key = "AIzaSyAy5fmQodq5Cf3UbFPxuEJ4nb6AavuuY_Q"

    [params.location.contact]
	    title = "Standort des Marktes:"
		company = "BZG – BegegnungsZentrum Gliesmarode"
		street = "Am Soolanger 1a"
		city = "38104 Braunschweig"

	# Footer
    [params.footer.facebook]
		link = "https://www.facebook.com/BSCastellum/"     
		
	[params.footer.photo]
	    title = "Fotos: Sarah Ringleb"