baseurl = "https://mittelaltermarkt-braunschweig.de"
languageCode = "de-de"
title = "Mittelalterliches Specktakel"
theme = "specktakel"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Thomas Rösler"
	description = "Mittelaltermarkt Braunschweig - Das 4. mittelalterliche Specktakel ist ein mittelatlericher Markt in Braunschweig-Gliesmarode."

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "Mittelalterliches Specktakel"

		[params.navigation.links]
			highlights = "Highlights"
			location = "Anfahrt"
			agenda = "Programm"
			contact = "Kontakt"

	# Hero section
	[params.hero]	     
		firstHeadline = "Mittelalterliches"
		secondHeadline = "Spe“c”ktakel"
		date = "31. + 01.09.2019"
		location = "Mittelaltermarkt<br>Braunschweig Gliesmarode"


	# About section
	[params.about]
		headline = "Seid gegrüßt, Freunde des mittelalterliches Treibens"
		description = """
nun zum 5. Mal Jährt sich das mittelalterliche  Spe“c”ktakel in Braunschweig. 
Wieder wird es auf dem alt bekannten Platz der ehemaligen Festwiese des Stadtteils Gliesmarode stattfinden. 
Nach einjähriger Pause gehen wir nun in einen Zweijahreszyklus über, dies ist leider aus Organisatorischen Gründen nötig geworden.
Aber nun ist es endlich wieder soweit. Merkt euch den Termin schon einmal gut, es gibt wieder viel zu erleben und mitmachen. 

**31.08. – 01.09.2019**

Als eines der Highlights sind dieses mal die Musikanten der Gruppe **Klanginferno**.

Wir haben wieder ein buntes Veranstaltungsprogramm zum Staunen, Mitmachen und Genießen für euch zusammengestellt und hoffen, euch wieder bestens unterhalten zu können. 
Für das leibliche Wohl ist natürlich auch wieder gesorgt:
Ob wohlschmeckendes Pfannenbrot, Bratwurst, Veganer Eintopf oder Met aus eigener Herstellung - hier ist für jeden etwas dabei.
Viel Spaß auf dem **5. mittelalterlichen Markt** wünschen euch die Organisatoren und alle Markttreibenden.
 
Euer Orgateam
"""

	[params.program]
		headline = "Weiters Angebot"

	[params.agenda]
		headline = "Programm\u00ADablauf"

	# Google Maps section
	[params.location]
	    headline = "Hier sind wir zu finden"
	 	latitude  = "52.2775"
	 	longitude = "10.5555"
	    address = "Am Soolanger 1, 38104 Braunschweig"
		content = "<b>BegegnungsZentrum</b><br>Am Soolanger 1<br>38104 Braunschweig"

    [params.location.contact]
	    title = "Standort des Marktes:"
		company = "BZG – BegegnungsZentrum Gliesmarode"
		street = "Am Soolanger 1a"
		city = "38104 Braunschweig"

#	[params.sponsoren]
#		headline = "Wir danken unseren Sponsoren"
#
#		[[params.sponsoren.items]]
#				image = "wolters.jpg"
#				link = "http://www.hofbrauhaus-wolters.de"
#
#		[[params.sponsoren.items]]
#				image = "alba.jpg"
#				link = "http://www.alba-bs.de"
#
#		[[params.sponsoren.items]]
#				image = "elite.jpg"
#				link = "http://www.elite24.net"
#
#		[[params.sponsoren.items]]
#				image = "wendt.jpg"
#
#		[[params.sponsoren.items]]
#				image = "mandrin.jpg"
#				link = "http://www.cafe-mandrin.de"
#
#		[[params.sponsoren.items]]
#				image = "schwieger.jpg"
#				link = "http://www.fleischereischwieger.de"

	# Footer
    [params.footer.facebook]
		link = "https://www.facebook.com/events/463825197327280"     
		
	[params.footer.photo]
	    title = "Fotos: Sarah Ringleb"