baseurl = "https://mittelaltermarkt-braunschweig.de"
languageCode = "de-de"
title = "Mittelalterliches Specktakel"
theme = "specktakel"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Thomas Rösler"
	description = "Mittelaltermarkt Braunschweig - Das 4. mittelalterliche Specktakel ist ein mittelatlericher Markt in Braunschweig-Gliesmarode."

	# The path must be relative to the static folder
	favicon = "favicon.ico"

	# Navigation
	[params.navigation]
		brand = "Mittelalterliches Specktakel"

		[params.navigation.links]
			highlights = "Highlights"
			location = "Anfahrt"
			agenda = "Programm"
			contact = "Kontakt"

	# Hero section
	[params.hero]	     
		firstHeadline = "Mittelalterliches"
		secondHeadline = "Spe“c”ktakel"
		date = "31.8. + 01.09.2019"
		location = "Mittelaltermarkt<br>Braunschweig Gliesmarode"


	# About section
	[params.about]
		headline = "Seid gegrüßt, Freunde des mittelalterliches Treibens"
		description = """
Das Begegnungszentrum Gliesmarode des SovD
veranstaltet nun wieder das Mittelalterliche Spe”c”ktakel am
 
__31.08 – 01.09.2019__.
 
Dank ihnen nun als erstes kleines Jubiläum zum 5.mal.
 
Nach dem großen Erfolg vom letzten Markt,den mehrere 1000 Besucher erleben konnten,
hat uns in unserer Arbeit gestärkt so das wir die bekannten Markttreibenden um einige
Attraktionen bereichern können.
 
Die Geschichtsreise findet wieder an einem Wochenende auf der ehemaligen Festwiese
Gliesmarode statt.
 
Ein buntes Rahmenprogramm für Groß und Klein zum staunen und mitmachen wurde von uns wieder zusammen gestellt.
Das Mittelalterliche Spe“c”ktakel werden wir auch in Zukunft nur noch alle 2 Jahre aus orgasinatorischen Gründen veranstalten können.
 
Wir würden uns über ihren Besuch sehr freuen und hoffen auf sonniges Wetter und gute Laune.
das Orgateam
"""

	[params.program]
		headline =  "Markt-Highlights"
		subheadline = "und weitere"
		#bottomline = "im Begegnungszentrum großes Kuchenbuffet, Kaffee und Kaffeespezialitäten"

	[params.agenda]
		headline = "Programm"

	# Google Maps section
	[params.location]
	    headline = "Hier sind wir zu finden"
	 	latitude  = "52.2775"
	 	longitude = "10.5555"
	    address = "Am Soolanger 1, 38104 Braunschweig"
		content = "<b>BegegnungsZentrum</b><br>Am Soolanger 1<br>38104 Braunschweig"

    [params.location.contact]
	    title = "Standort des Marktes:"
		company = "BZG – BegegnungsZentrum Gliesmarode"
		street = "Am Soolanger 1a"
		city = "38104 Braunschweig"

	[params.organization]
		headline = "Orgateam"
		subheadline = "weiteres Orgateam"

	[[params.organization.major]]
		name = "Thomas Rösler"

	[[params.organization.major]]
		name = "Jens Leipelt"

	[[params.organization.major]]
		name = "Boris Pawlik-Warnecke"

	[[params.organization.minor]]
		name = "Claudia Rösler"

	[[params.organization.minor]]
		name = "Ira Pawlik-Warnecke"

	[[params.organization.minor]]
		name = "Stefanie & Dennis Grimm"


	[params.sponsoren]
		headline = "Wir danken unseren Sponsoren"

		[[params.sponsoren.items]]
				image = "wolters.jpg"
				link = "http://www.hofbrauhaus-wolters.de"

		[[params.sponsoren.items]]
				image = "alba.jpg"
				link = "http://www.alba-bs.de"

		[[params.sponsoren.items]]
				image = "goerge.jpg"
				link = "https://goerge-markt.de"
#
#		[[params.sponsoren.items]]
#				image = "elite.jpg"
#				link = "http://www.elite24.net"
#
#		[[params.sponsoren.items]]
#				image = "wendt.jpg"
#
#		[[params.sponsoren.items]]
#				image = "mandrin.jpg"
#				link = "http://www.cafe-mandrin.de"
#
#		[[params.sponsoren.items]]
#				image = "schwieger.jpg"
#				link = "http://www.fleischereischwieger.de"

	# Footer
    [params.footer.facebook]
		link = "https://www.facebook.com/events/463825197327280"     
		
	[params.footer.photo]
	    title = "Fotos: Sarah Ringleb"