baseurl = "https://trichterwolke.github.io/specktakel/"
languageCode = "de-de"
title = "Mittelalterliches Specktakle"
theme = "specktakel"
googleAnalytics = ""

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at http://fontawesome.io/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more information take a look at the README.

	# To provide some metadata for search engines feel free to add some
	# information about you and your website.
	name = "Your name"
	description = "Your description"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Mittelalterliches Specktakel"

		[params.navigation.links]
			highlights = "Highlights"
			agenda = "Programm"
			contact = "Kontakt"
			location = "Standort"


	# Hero section
	[params.hero]
		# To change the background of the hero section, replace the 'header.jpg' at './static/img' with your own.
		#slogan     = "Your awesome slogan"
		#subtitle   = "[Lorem](//google.com) ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis nesciunt consequatur ut nihil voluptatem fugiat eos eveniet alias in veniam?"
		firstHeadline = "Mittelalterliches"
		secondHeadline = "Spe“c”ktakel"
		date = "23. + 24.09.2017"
		location = "Braunschweig Gliesmarode"
		buttonText = "Zeig’  mir mehr"


	# About section
	[params.about]
		headline    = "Seid gerüßt Freunde des mittelalterliches Treibens"
		description = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."
		buttonText  = "Get started!"

     # Achievement section
	 [params.achievement]
	 	headline = "Über uns"
		image = "achievement/wappen.png"
        description = "Der Name „Castellum ex varius contextum“ heißt frei übersetzt „Kleines Lager, welches Unterschiede vereint“. Wir möchten mit dieser Bezeichnung zum Ausdruck bringen, dass wir stolz sind solch eine vielfältige Gruppe aus verschiedenen Personen, verschiedener Altersgruppen mit verschiedenen beruflichen Schwerpunkten zu sein, die sich jedoch durch Freundschaft und das Interesse am Lagerleben vereint. Jeder ist verschieden, aber die Herzen schlagen gleich!"

    	# About section
	[params.activities]
		headline    = "Ein braunschweiger Heerlager"
		description = "Wir sind nicht nur in den Kampfkünsten geübt, sondern gehen auch einer Vielzahl von handwerklichen Tätigkeiten nach. Es ist uns wichtig, dass das Wissen unter den Mitgliedern weiter gegeben wird, um auf Märkten möglichst viel von unserer Kunst zeigen zu können."
    
	# Service section
#	[params.services]
#		headline = "At your service"

#        [[params.services.list]]
#            icon = "fa-diamond"
#            title = "Sturdy Templates"
#            description = "Our templates are updated regularly so they don't break."

#        [[params.services.list]]
#			icon = "fa-paper-plane"
#			title = "Ready to Ship"
#			description = "You can use this theme as is, or you can make changes!"

#		[[params.services.list]]
#            icon = "fa-newspaper-o"
#            title = "Up to Date"
#            description = "We update dependencies to keep things fresh."

#        [[params.services.list]]
#            icon = "fa-heart"
#            title = "Made with Love"
#            description = "You have to make your websites with love these days!"

	[params.program]

	[[params.program.items]]
			title = "Schmiede"
			
	[[params.program.items]]
			title = "Hornarbeiten"
			
	[[params.program.items]]
			title = "Steinmetz"
			
	[[params.program.items]]
			title = "Lederarbeiten"
			
	[[params.program.items]]
			title = "Kinderprogramm mit Quiz"
			
	[[params.program.items]]
			title = "Glasperlen"
			
	[[params.program.items]]
			title = "Diamantensieben"

	[[params.program.items]]
			title = "Tanzvorführung"
			
	[[params.program.items]]
			title = "Steinmetz"
			
	[[params.program.items]]
			title = "Showkampf"
			
	[[params.program.items]]
			title = "Pfannenbrotherstellung"
			
	[[params.program.items]]
			title = "Gewandschneiderei"
			
	[[params.program.items]]
			title = "Lagerwache"


    # Portfolio modals
	[params.portfolio.modal]
        client = "Client"
        date = "Date"
        category = "Category"
        buttonText = "Close"

    # Aside section
	[params.aside]
		headline = "Get the Creative Theme for Hugo"

		[params.aside.button]
			text = "Download now"
			link = "//github.com/digitalcraftsman/hugo-creative-theme"

	# Contact section
	[params.contact]
		headline = "Let's Get In Touch!"
		description = "Ready to start your next project with us? That's great! Give us a call or send us an email and we will get back to you as soon as possible!"
		phone = "+49 160 97363699"
		email = "trichterwolke@outlook.com"
		facebook = "https://facebook.com/BSCastellum"

	# Google Maps section
	 [params.location]
	 	latitude  = "52.27721"
	 	longitude = "10.55484"
	    adress = "Am Soolanger 1, 38104 Braunschweig"
#	 	maps_api_key = ""
